/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_XLog */

#ifndef _Included_com_example_XLog
#define _Included_com_example_XLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_XLog
 * Method:    nativeInitLog
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_example_XLog_nativeInitLog
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_example_XLog
 * Method:    nativeCloseLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_XLog_nativeCloseLog
  (JNIEnv *, jclass);

/*
 * Class:     com_example_XLog
 * Method:    nativelog
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_XLog_nativelog
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     com_example_XLog
 * Method:    nativeFlushLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_XLog_nativeFlushLog
  (JNIEnv *, jclass);

/*
 * Class:     com_example_XLog
 * Method:    nativeSwitchStdOut
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_example_XLog_nativeSwitchStdOut
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
